name: Build, Test, Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Run Makefile build for Development
        run: |
          ./reports.sh
          export GO111MODULE=on
          go mod vendor
          make build
          test -f bin/linux_amd64/app
          make all-container
          docker images | grep "^ghcr.io/martinheinz/go-github-app/app.*__linux_amd64"
          make ci
      - name: SonarCloud scanner
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Send report to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}